logging:
  level: INFO
  loggers:
    nl.knaw.huygens: DEBUG

swagger:
  resourcePackage: nl.knaw.huygens.hypercollate.dropwizard.resources
  
baseURI: http://127.0.0.1:8080/

pathToDotExecutable: C:/Program Files (x86)/Graphviz2.38/bin/dot.exe