# The base URI with ip name/address and port for the server to run on
# note: the port number in the baseURI should match the server/applicationConnectors/port setting below
baseURI: http://localhost:2018/

# optional path to dot executable for rendering dot to svg/png
# uncomment and set when auto-detecting does not work.
#pathToDotExecutable: /usr/bin/dot
#or
#pathToDotExecutable: /usr/local/bin/dot

server:
  applicationConnectors:
  - type: http
    port: 2018

logging:
  level: INFO
  loggers:
    nl.knaw.huygens: WARN
