# The base URI with ip name/address and port for the server to run on
# note: the port number in the baseURI should match the server/applicationConnectors/port setting below
baseURI: http://localhost:9000/

# optional path to dot executable for rendering dot to svg/png
# uncomment and set when autodetecting does not work.
#pathToDotExecutable: /usr/bin/dot

server:
  applicationConnectors:
  - type: http
    port: 9000

logging:
  level: INFO
  loggers:
    nl.knaw.huygens: DEBUG

# DO NOT CHANGE THESE SETTINGS:
swagger:
  resourcePackage: nl.knaw.huygens.hypercollate.rest.resources
